### ISSUE TITLE
Question: Have you plans to open source codes?

### ISSUE THREAD

**Issue by korabelnikov** [IBBM/Cascaded-FCN#1]

**Comment by mohamed-ezz** [comment]
In principle we would love to open source it. However since the code has gone through many experiment iterations, it needs polishing before we can publish it. Unfortunately at this point we don't have enough resources to do that.

However we will soon provide an ipython notebook which shows an example of running the network to predict segmentation for a volume.
Are you looking for code to use the network for inference or do you want to retrain ?

**Comment by korabelnikov** [comment]
@mohamed-ezz  Thanks for a fast response.
I want to repeat your results and cite your paper

**Comment by mohamed-ezz** [comment]
Although we haven't made the code officially public, you can find the code at https://github.com/mohamed-ezz/saratan

Since this is not official, you may find the code not well documented and - as mentioned - might need some cleanup.

**Comment by korabelnikov** [comment]
@mohamed-ezz Thanks!
