### ISSUE TITLE
training data format

### ISSUE THREAD

**Issue by idinsmore1** [IBBM/Cascaded-FCN#36]
Hi there,

I was wondering what the format of the data was for you when you did the training of this model? I understand the preprocessing steps for the example, but when the training happened was it loaded in through .npy files? I was trying to figure it out by looking through https://github.com/mohamed-ezz/saratan/blob/master/notebooks/realtime_train.ipynb but was having issues. Thanks for your help.

**Comment by mohamed-ezz** [comment]
It's been a long while since I touched this code but I think you're correct...seems that data during training was in .npy format.

This first layer here https://github.com/mohamed-ezz/saratan/blob/master/notebooks/unet-overfit-python.prototxt#L11
has type numpy_data_layer. It's a custom layer defined here https://github.com/mohamed-ezz/saratan/blob/master/data/layers/numpy_data_layer.py

**Comment by idinsmore1** [comment]
Ah I see, missed this before. Thanks!
